# config file version
apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: default
      port: 8123
      server: clickhouse
      protocol: http
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    editable: false