{
 "title": "Java Instrumentation Benchmarks",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  {
   "title": "Thread switch rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Thread switch rate'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Req. p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Req. p95 (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Iter. p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Iter. p95 (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Net write avg (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Net write avg (bps)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Avg. mch tot cpu %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Avg. mch tot cpu %'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Iter. mean (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Iter. mean (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Net read avg (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Net read avg (bps)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Req. mean (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Req. mean (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Min heap used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Min heap used (MB)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Max heap used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Max heap used (MB)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Peak threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Peak threads'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Max. CPU (user) %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Max. CPU (user) %'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Startup time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Startup time (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "GC time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'GC time (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "GC pause time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'GC pause time (ms)'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Avg. CPU (user) %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Avg. CPU (user) %'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Total allocated MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    MetricName,\n    StartTimeUnix,\n    MAX(IF(Attributes['entity'] = 'none', Value, NULL)) AS none,\n    MAX(IF(Attributes['entity'] = 'snapshot', Value, NULL)) AS snapshot,\n    MAX(IF(Attributes['entity'] = 'latest', Value, NULL)) AS latest\nFROM otel.otel_metrics_sum\nWHERE MetricName = 'Total allocated MB'\nGROUP BY MetricName, StartTimeUnix\nORDER BY StartTimeUnix;",
     "selectedFormat": 4
    }
   ]
  }
 ]
}